### PR TITLE
Validate decimal range

### LINKED ISSUE #35: Validate decimal range
It would be great if schema_validations could add a validation for decimal / numeric range. These fields are defined with a precision (total number of digits) and scale (number of fractional digits).

So the range for a decimal column with precision 4 and scale 2 is ±99.99 or < 10^2 and > -10^2 using the formula abs(10^(precision - scale)).

This can be expressed as an ActiveRecord validation:

```ruby
validates :foo, numericality: { less_than: 10**2, greater_than: -10**2 } 
```

Here's the error you get on postgres, when the value overflows:

```sql
SELECT 100.99::numeric(4,2);
ERROR:  numeric field overflow
DETAIL:  A field with precision 4, scale 2 must round to an absolute value less than 10^2.
```

### PR DESCRIPTION
**Pull request by felixbuenemann**
The range of decimal columns is limited by the number of numerals (precision) and decimals (scale).

**Example:**

The range for a decimal column with precision 4 and scale 2 is ±99.99
or < 10^2 and > -10^2 using the formula abs(10^(precision - scale)).

This resolves #35.

### CODE REVIEW

**Comment by ronen** [comment]
Cool.  Update the README too?

**Comment by felixbuenemann** [comment]
Oh, forgot about the README. I'll look into it.

**Comment by felixbuenemann** [comment]
OK, updated the data types table in the README.

**Comment by ronen** [comment]
Cool again!  I've released version 2.1.0 with this merged in.

Thanks for taking the time

**Pull request merged**
