### PR TITLE
add in AR 6.1 and 7.0 support, also Ruby 3.1

### PR DESCRIPTION
**Pull request by urkle**

### CODE REVIEW

**Review by felipemaier — APPROVED** [review]

**Comment by EdwardCaulfield** [comment]
Is there any view towards when this update will be released for the gem?  Is there any work that I can help with to bring this along?

**Comment by urkle** [comment]
> Is there any view towards when this update will be released for the gem? Is there any work that I can help with to bring this along?

This is just waiting on me to do the final sanity check and release it. (along with other dependent gems).   I have 10 gems to release in the milestone.  I will be getting to releasing them this week.

**Comment by EdwardCaulfield** [comment]
Wonderful!  Thank you very much!

**Comment by urkle** [comment]
@EdwardCaulfield the new version is now released.

**Pull request merged**
